import React from "react";

export const elements = [
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
  "simple text",
  <span style={{ color: "green" }}>component</span>,
];
